package com.cristian.app.lox;

public enum TokenType {
    // SINGLE CHAR TOKEN
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS,
    PLUS, SEMICOLON, SLASH, STAR,

    // SINGLE OR TWO CHAR TOKENS
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,

    // LITERALS
    IDENTIFIER, STRING, NUMBER,

    // KEYWORDS
    AND, CLASS, ELSE, FALSE, TRUE, IF, WHILE, FOR, FUN, NIL, OR, PRINT, RETURN, SUPER,
    THIS, VAR, BREAK,

    EOF
}
